export enum GameType {
  UNDETECTABLE = "UNDETECTABLE",
  WINDOWS_SETUP = "WINDOWS_SETUP",
  WINDOWS_PORTABLE = "WINDOWS_PORTABLE",
  WINDOWS_SOFTWARE = "WINDOWS_SOFTWARE",
  LINUX_PORTABLE = "LINUX_PORTABLE",
  LINUX_SOFTWARE = "LINUX_SOFTWARE",
  LINUX_SETUP = "LINUX_SETUP",
}
